name: Hedera Mirror Node Explorer Coverage Report

on: [ workflow_dispatch ]

jobs:

  coverage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run test:unit
